# Linux MIPS
[[target]]
os = "ubuntu-latest"
target = "mips-unknown-linux-musl"
release-name = "mips-unknown-linux-musl"
tool = "cross"
extra-args = "--no-default-features -F standard,ring -Z build-std=std,panic_abort"
build-std = true
skip-test = true
